version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - static:/static
    depends_on:
      - web
    networks:
      - webnet
  
  web:
    build: ./djangoproject
    container_name: graphql_app
    command: "gunicorn myapp.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    networks:
      - webnet

networks:
  webnet:
    name: django_network
volumes:
  static:


