# Generated by Django 5.0.6 on 2024-06-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappapp', '0002_author_book_userprofile_delete_course_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Item',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='biography',
            new_name='description',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
