# Generated by Django 5.0.6 on 2024-07-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappapp', '0004_author_book_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default=1, upload_to='book_images'),
            preserve_default=False,
        ),
    ]
